# Generated by Django 4.1.1 on 2022-12-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='activo',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
        migrations.AddField(
            model_name='clientes',
            name='activo',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(blank=True, choices=[('S', 'Sin stock'), ('C', 'Con Stock')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1),
        ),
    ]
