# Generated by Django 4.1.1 on 2022-12-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_activo_activo_clientes_activo_alter_activo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.BooleanField(max_length=50),
        ),
    ]
