# Generated by Django 4.1.1 on 2022-11-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activo',
            fields=[
                ('id_activo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_activo', models.CharField(max_length=32)),
                ('cantidad', models.IntegerField()),
                ('precio', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id_permisos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='roles_permisos',
            fields=[
                ('id_roles_permisos', models.IntegerField(primary_key=True, serialize=False)),
                ('permisos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='inventario.permisos')),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='inventario.roles')),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('us_id', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=32)),
                ('segundo_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('primer_apellido', models.CharField(max_length=32)),
                ('segundo_apellido', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('nro_telefono', models.CharField(max_length=32, unique=True)),
                ('psw', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('roles', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='inventario.roles')),
            ],
        ),
        migrations.CreateModel(
            name='maquinaria',
            fields=[
                ('cod_maquinaria', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('diseño_maquinaria', models.FileField(max_length=70, upload_to='')),
                ('material_estructura', models.CharField(max_length=200)),
                ('activo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='inventario.activo')),
            ],
        ),
        migrations.CreateModel(
            name='herramientas',
            fields=[
                ('cod_herramienta', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=100)),
                ('activo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='inventario.activo')),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('rut_cliente', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=32)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('maquinaria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='inventario.maquinaria')),
            ],
        ),
    ]
