# Generated by Django 4.1.2 on 2022-10-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activo',
            name='id_activo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personas',
            name='us_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles_permisos',
            name='id_roles_permisos',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
