# Generated by Django 4.1.1 on 2022-11-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_maquinaria_clientes_maquinariac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramientas',
            old_name='activoh',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='activom',
            new_name='activo',
        ),
    ]
