# Generated by Django 4.1.1 on 2022-11-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_activoh_herramientas_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='activo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='inventario.activo'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='activo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='inventario.activo'),
        ),
    ]
