# Generated by Django 4.1.2 on 2022-10-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_activo_cantidad_alter_activo_id_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='id_rol',
            new_name='id_permisos',
        ),
    ]
