# Generated by Django 4.1.2 on 2022-10-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_id_rol_permisos_id_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='maquinaria',
            fields=[
                ('cod_maquinaria', models.IntegerField(primary_key=True, serialize=False)),
                ('diseño_maquinaria', models.FileField(max_length=70, upload_to='')),
                ('material_estructura', models.CharField(max_length=50)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='inventario.activo')),
            ],
        ),
        migrations.CreateModel(
            name='herramientas',
            fields=[
                ('cod_herramienta', models.IntegerField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=100)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='inventario.activo')),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=13)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='inventario.maquinaria')),
            ],
        ),
    ]
