# Generated by Django 4.0.1 on 2022-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_activo_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre_activo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='activo',
            name='precio',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='cod_herramienta',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='cod_maquinaria',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
