# Generated by Django 4.0.1 on 2022-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_activo_nombre_activo_alter_activo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='material_estructura',
            field=models.CharField(max_length=200),
        ),
    ]
